name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install tools
        run: |
          export GOBIN="$(go env GOPATH)/bin"
          go install golang.org/x/tools/cmd/goimports@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GOBIN" latest

      - name: Go fmt check
        run: |
          gofmt -l . | tee /tmp/gofmt.out
          test ! -s /tmp/gofmt.out

      - name: Goimports check
        run: |
          $(go env GOPATH)/bin/goimports -l . | tee /tmp/goimports.out
          test ! -s /tmp/goimports.out

      - name: Go vet
        run: go vet ./...

      - name: GolangCI-Lint
        run: $(go env GOPATH)/bin/golangci-lint run

      - name: Go test
        run: go test ./...
